jwt:
  TOKEN_EXPIRED_IN: 60m
  TOKEN_MAXAGE: 3600
  TOKEN_SECRET: "event_bright"

docker_database:
  POSTGRESQL_ADDON_HOST: database
  POSTGRESQL_ADDON_PORT: 5432
  POSTGRESQL_ADDON_DB: event_bright
  POSTGRESQL_ADDON_USER: admin
  POSTGRESQL_ADDON_PASSWORD: secret


local_db:
  POSTGRESQL_ADDON_DB:  db_name 
  POSTGRESQL_ADDON_HOST:  host 
  POSTGRESQL_ADDON_PASSWORD:  password 
  POSTGRESQL_ADDON_PORT:  port 
  POSTGRESQL_ADDON_USER:  user 


current_db:
  RUNNING: remote_db

#  psql 'postgres://mokhlesurr031:lO1XJIuP0Ugw@ep-proud-salad-438084.ap-southeast-1.aws.neon.tech/neondb'


