jwt:
  TOKEN_EXPIRED_IN: 60m
  TOKEN_MAXAGE: 3600
  TOKEN_SECRET: "event_bright"

docker_database:
  POSTGRESQL_ADDON_HOST: database
  POSTGRESQL_ADDON_PORT: 5432
  POSTGRESQL_ADDON_DB: event_bright
  POSTGRESQL_ADDON_USER: admin
  POSTGRESQL_ADDON_PASSWORD: secret


local_db:
  POSTGRESQL_ADDON_DB:  neondb 
  POSTGRESQL_ADDON_HOST:  ep-proud-salad-438084.ap-southeast-1.aws.neon.tech
  POSTGRESQL_ADDON_PASSWORD:  lO1XJIuP0Ugw 
  POSTGRESQL_ADDON_PORT:  5432 
  POSTGRESQL_ADDON_USER:  mokhlesurr031 

remote_db:
  POSTGRESQL_ADDON_DB:  ${{ secrets.POSTGRESQL_ADDON_DB }}
  POSTGRESQL_ADDON_HOST:  ${{ secrets.POSTGRESQL_ADDON_HOST }}
  POSTGRESQL_ADDON_PASSWORD:  ${{ secrets.POSTGRESQL_ADDON_PASSWORD }}
  POSTGRESQL_ADDON_PORT:  ${{ secrets.POSTGRESQL_ADDON_PORT }}
  POSTGRESQL_ADDON_USER:  ${{ secrets.POSTGRESQL_ADDON_USER }}


current_db:
  RUNNING: local_db

#  psql 'postgres://mokhlesurr031:lO1XJIuP0Ugw@ep-proud-salad-438084.ap-southeast-1.aws.neon.tech/neondb'


