jwt:
  TOKEN_EXPIRED_IN: 60m
  TOKEN_MAXAGE: 3600
  TOKEN_SECRET: "event_bright"

docker_database:
  POSTGRESQL_ADDON_HOST: database
  POSTGRESQL_ADDON_PORT: 5432
  POSTGRESQL_ADDON_DB: event_bright
  POSTGRESQL_ADDON_USER: admin
  POSTGRESQL_ADDON_PASSWORD: secret


remote_db:
  POSTGRESQL_ADDON_DB: { { db } }
  POSTGRESQL_ADDON_HOST: { { host } }
  POSTGRESQL_ADDON_PASSWORD: { { password } }
  POSTGRESQL_ADDON_PORT: { { port } }
  POSTGRESQL_ADDON_URI: { { url } }
  POSTGRESQL_ADDON_USER: { { user } }
  POSTGRESQL_ADDON_VERSION: { { version } }

local_db:
  POSTGRESQL_ADDON_DB: { { db_name } }
  POSTGRESQL_ADDON_HOST: { { host } }
  POSTGRESQL_ADDON_PASSWORD: { { password } }
  POSTGRESQL_ADDON_PORT: { { port } }
  POSTGRESQL_ADDON_USER: { { user } }


current_db:
  RUNNING: docker_database




