jwt:
  TOKEN_EXPIRED_IN: 60m
  TOKEN_MAXAGE: 3600
  TOKEN_SECRET: "event_bright"

docker_database:
  POSTGRESQL_ADDON_HOST: database
  POSTGRESQL_ADDON_PORT: 5432
  POSTGRESQL_ADDON_DB: event_bright
  POSTGRESQL_ADDON_USER: admin
  POSTGRESQL_ADDON_PASSWORD: secret


remote_db:
  POSTGRESQL_ADDON_DB:  ${{ secrets.POSTGRESQL_ADDON_DB }}
  POSTGRESQL_ADDON_HOST:  ${{ secrets.POSTGRESQL_ADDON_HOST }}
  POSTGRESQL_ADDON_PASSWORD:  ${{ secrets.POSTGRESQL_ADDON_PASSWORD }}
  POSTGRESQL_ADDON_PORT:  ${{ secrets.POSTGRESQL_ADDON_PORT }}
  POSTGRESQL_ADDON_USER:  ${{ secrets.POSTGRESQL_ADDON_USER }}


current_db:
  RUNNING: remote_db


