jwt:
  TOKEN_EXPIRED_IN: 60m
  TOKEN_MAXAGE: 3600
  TOKEN_SECRET: "event_bright"

docker_database:
  POSTGRESQL_ADDON_HOST: database
  POSTGRESQL_ADDON_PORT: 5432
  POSTGRESQL_ADDON_DB: event_bright
  POSTGRESQL_ADDON_USER: admin
  POSTGRESQL_ADDON_PASSWORD: secret


neon_db:
  POSTGRESQL_ADDON_DB: neondb
  POSTGRESQL_ADDON_HOST: ep-winter-shadow-337023.ap-southeast-1.aws.neon.tech
  POSTGRESQL_ADDON_PASSWORD: mdoDKH32WfRU
  POSTGRESQL_ADDON_PORT: 5432
  POSTGRESQL_ADDON_URI: postgres://mokhlesurr031@ep-winter-shadow-337023.ap-southeast-1.aws.neon.tech/neondb
  POSTGRESQL_ADDON_USER: mokhlesurr031
  POSTGRESQL_ADDON_VERSION: 14


current_db:
  RUNNING: neon_db




