docker_database:
  POSTGRESQL_ADDON_HOST: localhost
  POSTGRESQL_ADDON_PORT: 5432
  POSTGRESQL_ADDON_DB: event_bright
  POSTGRESQL_ADDON_USER: admin
  POSTGRESQL_ADDON_PASSWORD: secret


current_db:
  RUNNING: docker_database


jwt:
  TOKEN_EXPIRED_IN: 3600
  TOKEN_MAXAGE: 3600
  TOKEN_SECRET: "event_bright"

