version: '3.1'

services:

  database:
    image: postgres
    container_name: pg-event-bright
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=event_bright
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./database:/var/lib/postgresql
#    networks:
#      - internal

#  app:
#    build:
#      context: .
#    ports:
#      - "8081:8081"
#    depends_on:
#      - database
#    networks:
#      - internal
#    environment:
#      - POSTGRESQL_ADDON_HOST=database


#networks:
#  internal:
