version: '3.1'

services:

  database:
    image: postgres
    restart: always
    container_name: event_bright_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=event_bright
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./database:/var/lib/postgresql

  app:
    image: event_bright
    container_name: event_bright_app
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - POSTGRESQL_ADDON_HOST=database
      - POSTGRESQL_ADDON_PORT=5432
      - POSTGRESQL_ADDON_USER=admin
      - POSTGRESQL_ADDON_PASSWORD=secret
      - POSTGRESQL_ADDON_DB=event_bright
    depends_on:
      - database

