name: Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to latest code
        uses: actions/checkout@v2

      - name: Build latest change
        run: go build -v ./...

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 1.0.0
          repository: mahin96/event-bright
        env:
          DOCKER_USERNAME: "mahin96"
          DOCKER_PASSWORD: "@mahinoyela@"

