name: Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to latest code
        uses: actions/checkout@v2

      - name: Build latest change
        run: go build -v ./...


      - name: Login to Docker Hub
      uses: ./
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
