name: Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to latest code
        uses: actions/checkout@v2

      - name: Build latest change
        run: go build -v ./...

      # - name: Build Docker Image
      #   run: |
      #     docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_ACCESS_TOKEN }}" docker.io
      #     docker build -t event-bright:1.0.0 .
      #     # echo "${{ secrets.DOCKER_ACCESS_TOKEN }}"

      - name: Login to Docker Hub
        uses: ./
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/event-bright:1.0.0