name: Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: https://hub.docker.com/repository/docker/mahin96/event-bright/general
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mahin96/event-bright:1.0.0

#      - name: Deploy to EC2
#        uses: appleboy/ssh-action@master
#        with:
#          host: 54.169.156.112
#          username: ubuntu
#          key: ${{ secrets.EC2_PRIVATE_KEY }}
#          port: 22
#          script: |
#            docker pull mahin96/event-bright:latest
#            docker-compose up -d
