name: Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to latest code
        uses: actions/checkout@develop

      - name: Build latest change
        run: go build -v ./...

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag eb-app:$(date +$s)
